### PR TITLE
Update input_methods_settings.xml

### PR DESCRIPTION
**Pull request by WimN**
on lockscreen the devices freeces after putting in a pin number, nothing will work anymore even after reboot the pin number is not working, maybe its because there was no new line at the end of the file

### CODE REVIEW

**Comment by Martinusbe** [comment]
Suppose there is on with authorship

**Comment by premaca** [comment]
How long is your PIN number? I remember @psyafter picked Nougat PIN 4 numbers commit but later he picked Oreo commits to support arbitrary PIN lengths. I haven't tested recent and i'm on Gzosp. 
New line shouldn't have any affect.

**Comment by WimN** [comment]
Ik had 4 cijfers gebruikt maar bij het invulken was er niets te zien de
cursur verplaatste zich wel, na het 2de maal invullen bevroor het hele
systeem, daarna was de lockscreen niet meer te openen zonder pincode


Op do 19 apr. 2018 16:48 schreef Prema Chand A <notifications@github.com>:

**Comment by Martinusbe** [comment]
and does this fix that?

**Comment by psyafter** [comment]
i have no problems even w/o pr

**Pull request closed without merging**
